package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	graphql1 "hub-control-plane/backend/graphql"
	"hub-control-plane/backend/models"
)

// Tags is the resolver for the tags field.
func (r *contactResolver) Tags(ctx context.Context, obj *models.ContactEntity) ([]string, error) {
	panic(fmt.Errorf("not implemented: Tags - tags"))
}

// User is the resolver for the user field.
func (r *contactResolver) User(ctx context.Context, obj *models.ContactEntity) (*models.UserEntity, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input graphql1.CreateUserInput) (*models.UserEntity, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input graphql1.UpdateUserInput) (*models.UserEntity, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// CreateContact is the resolver for the createContact field.
func (r *mutationResolver) CreateContact(ctx context.Context, input graphql1.CreateContactInput) (*models.ContactEntity, error) {
	panic(fmt.Errorf("not implemented: CreateContact - createContact"))
}

// UpdateContact is the resolver for the updateContact field.
func (r *mutationResolver) UpdateContact(ctx context.Context, id string, userID string, input graphql1.UpdateContactInput) (*models.ContactEntity, error) {
	panic(fmt.Errorf("not implemented: UpdateContact - updateContact"))
}

// DeleteContact is the resolver for the deleteContact field.
func (r *mutationResolver) DeleteContact(ctx context.Context, id string, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteContact - deleteContact"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*models.UserEntity, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int, offset *int) ([]*models.UserEntity, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Contact is the resolver for the contact field.
func (r *queryResolver) Contact(ctx context.Context, id string, userID string) (*models.ContactEntity, error) {
	panic(fmt.Errorf("not implemented: Contact - contact"))
}

// Contacts is the resolver for the contacts field.
func (r *queryResolver) Contacts(ctx context.Context, limit *int, offset *int) ([]*models.ContactEntity, error) {
	panic(fmt.Errorf("not implemented: Contacts - contacts"))
}

// UserContacts is the resolver for the userContacts field.
func (r *queryResolver) UserContacts(ctx context.Context, userID string, favorites *bool) ([]*models.ContactEntity, error) {
	panic(fmt.Errorf("not implemented: UserContacts - userContacts"))
}

// UserDashboard is the resolver for the userDashboard field.
func (r *queryResolver) UserDashboard(ctx context.Context, userID string) (*graphql1.UserDashboard, error) {
	panic(fmt.Errorf("not implemented: UserDashboard - userDashboard"))
}

// SystemStats is the resolver for the systemStats field.
func (r *queryResolver) SystemStats(ctx context.Context) (*graphql1.SystemStats, error) {
	panic(fmt.Errorf("not implemented: SystemStats - systemStats"))
}

// Contacts is the resolver for the contacts field.
func (r *userResolver) Contacts(ctx context.Context, obj *models.UserEntity, limit *int, favorites *bool) ([]*models.ContactEntity, error) {
	panic(fmt.Errorf("not implemented: Contacts - contacts"))
}

// Contact returns graphql1.ContactResolver implementation.
func (r *Resolver) Contact() graphql1.ContactResolver { return &contactResolver{r} }

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

// User returns graphql1.UserResolver implementation.
func (r *Resolver) User() graphql1.UserResolver { return &userResolver{r} }

type contactResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
