// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"hub-control-plane/backend/models"
)

type CreateContactInput struct {
	UserID     string   `json:"userId"`
	Name       string   `json:"name"`
	Email      *string  `json:"email,omitempty"`
	Phone      *string  `json:"phone,omitempty"`
	Company    *string  `json:"company,omitempty"`
	IsFavorite *bool    `json:"isFavorite,omitempty"`
	Tags       []string `json:"tags,omitempty"`
}

type CreateUserInput struct {
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Mutation struct {
}

type Query struct {
}

type SystemStats struct {
	TotalUsers    int `json:"totalUsers"`
	TotalContacts int `json:"totalContacts"`
}

type UpdateContactInput struct {
	Name       *string  `json:"name,omitempty"`
	Email      *string  `json:"email,omitempty"`
	Phone      *string  `json:"phone,omitempty"`
	Company    *string  `json:"company,omitempty"`
	IsFavorite *bool    `json:"isFavorite,omitempty"`
	Tags       []string `json:"tags,omitempty"`
}

type UpdateUserInput struct {
	Email     *string `json:"email,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
}

type UserDashboard struct {
	User         *models.UserEntity      `json:"user"`
	Contacts     []*models.ContactEntity `json:"contacts"`
	ContactCount int                     `json:"contactCount"`
}
